# Docker Compose file for local development.
# db: has a volume to persist data.
# db-test: is ephemeral to be used for unit and e2e tests.

volumes:
  postgres:
  keycloak-postgres:

services:
  db:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  db-test:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'

  keycloak-postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    depends_on:
      - keycloak-postgres
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
